steps:
  - task: NodeTool@0
    displayName: Install Node.JS
    inputs:
      versionSpec: '12.x'

  - script: |
      yarn install --ignore-engines --frozen-lockfile --ignore-optional
    displayName: yarn install
