steps:
  - script: npx nps prepare.electron
    displayName: build electron

  - script: npx nps e2e.ci2.fixtures
    displayName: e2e fixtures (ci2)

  - script: npx nps e2e.ci2
    displayName: e2e tests (ci2)
