jobs:
- job: ci1_electron
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: build/ci1.electron.yml

- job: ci2_electron
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: build/ci2.electron.yml
