jobs:
- job: format_lint_test
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: .azure-pipelines/steps/install-dependencies.yml
  - template: .azure-pipelines/jobs/format-lint-test.yml

- job: package
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: .azure-pipelines/steps/install-dependencies.yml
  - template: .azure-pipelines/jobs/package.yml
