jobs:
- job: linux_shard_1
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: .azure-pipelines/steps/install-dependencies.yml
  - template: .azure-pipelines/jobs/ci1.linux.yml

- job: linux_shard_2
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: .azure-pipelines/steps/install-dependencies.yml
  - template: .azure-pipelines/jobs/ci2.linux.yml

- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: .azure-pipelines/steps/install-dependencies.yml
  - template: .azure-pipelines/jobs/windows.yml
