#!/usr/bin/env node
'use strict';

const { execSync } = require('child_process');
const { dirSync } = require('tmp');
const path = require('path');

const ngNewArgs = process.argv.slice(2);
const collection = (
  ngNewArgs.find(arg => arg.startsWith('--collection=')) ||
  '--collection=@schematics/angular'
).replace('--collection=', '');

try {
  // check the correct version of the NPM is installed
  const output = execSync('npm --version').toString();
} catch (e) {
  throw new Error('Cannot find npm. Do you have node installed?');
}

const tmpDir = dirSync().name;

console.log(`npm init -y`);
execSync('npm init -y', { cwd: tmpDir, stdio: [0, 1, 2] });
console.log(`npm install @angular/cli@latest`);
execSync('npm install @angular/cli@latest', {
  cwd: tmpDir,
  stdio: [0, 1, 2]
});

if (collection !== '@schematics/angular') {
  console.log(`npm install ${collection}@latest`);
  execSync(`npm install ${collection}@latest`, {
    cwd: tmpDir,
    stdio: [0, 1, 2]
  });
}

console.log(`ng new ${ngNewArgs.join(' ')}`);
execSync(
  `${path.join(tmpDir, 'node_modules', '.bin', 'ng')} new ${ngNewArgs.join(
    ' '
  )} --no-interactive`,
  {
    stdio: [0, 1, 2]
  }
);
