# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            keys:
              - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
              - v2-deps-{{ .Branch }}
              - v2-deps
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ./tmp
      # we should use- run: yarn start e2e.prepare
      - run: yarn start build.electron
      - run: yarn start dev.copy-assets.electron
      - run: yarn start e2e.fixtures
      - run: yarn start format.check
      - run: yarn start lint.affected.origin-master
      - run: yarn start test.affected.origin-master
      - run:
          command: yarn start e2e.ci
          no_output_timeout: 5m
          environment:
            CYPRESS_RECORD_KEY: b8ec9ad7-505f-48bb-9990-e8d5627bac26
