# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.6.0-stretch-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-dependencies-12.6.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-dependencies-12.6.0-{{ .Branch }}-
            # fallback to using the latest cache if no exact match is found
            - yarn-dependencies-12.6.0-
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: yarn-dependencies-12.6.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run: yarn start format.and.lint.check
      - run: yarn start prepare.e2e
      - run: yarn start test.affected.origin-master
      - run:
          command: yarn start e2e.ci1
          no_output_timeout: 5m
          environment:
            CYPRESS_RECORD_KEY: b8ec9ad7-505f-48bb-9990-e8d5627bac26

  cypress-2:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-dependencies-12.6.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-dependencies-12.6.0-{{ .Branch }}-
            # fallback to using the latest cache if no exact match is found
            - yarn-dependencies-12.6.0-
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn start prepare.e2e
      - run:
          command: yarn start e2e.ci2
          no_output_timeout: 5m
          environment:
            CYPRESS_RECORD_KEY: b8ec9ad7-505f-48bb-9990-e8d5627bac26

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - cypress-2
