distribute-on:
  small-changeset: 2 linux-medium-plus-js, 1 linux-large-js
  medium-changeset: 3 linux-medium-plus-js, 1 linux-large-js
  large-changeset: 6 linux-medium-plus-js, 1 linux-large-js

assignment-rules:
  - projects:
      - intellij
    runs-on:
      - linux-large-js
    parallelism: 1
