distribute-on:
  small-changeset: 3 linux-large-plus-js, 1 linux-medium-plus-js
  medium-changeset: 4 linux-large-plus-js, 1 linux-medium-plus-js
  large-changeset: 6 linux-large-plus-js, 1 linux-medium-plus-js

assignment-rules:
  - projects:
      - intellij
    runs-on:
      - linux-medium-plus-js
    parallelism: 1
