distribute-on:
  small-changeset: 1 linux-medium-plus-js, 1 linux-large-js, 1 linux-large-java
  medium-changeset: 2 linux-medium-plus-js, 1 linux-large-js, 1 linux-large-java
  large-changeset: 5 linux-medium-plus-js, 1 linux-large-js, 1 linux-large-java

assignment-rules:
  - projects:
      - intellij
    runs-on:
      - linux-large-java
