distribute-on:
  small-changeset: 3 linux-large-js
  medium-changeset: 4 linux-large-js
  large-changeset: 6 linux-large-js

assignment-rules:
  - projects:
      - intellij
    runs-on:
      - linux-large-js
    parallelism: 1
