distribute-on:
  small-changeset: 2 linux-medium-plus-js, 1 linux-large-js
  medium-changeset: 3 linux-medium-plus-js, 1 linux-large-js
  large-changeset: 5 linux-medium-plus-js, 1 linux-large-js

assignment-rules:
  - project: intellij
    target: build
    runs-on:
      - linux-large-js
