export * from './lib/abstract-tree-provider';
export * from './lib/read-projects';
export * from './lib/empty-state-messages';
export { watchFile } from './lib/watch-file';
export { getShellExecutionForConfig } from './lib/shell-execution';
export { getWorkspacePath } from './lib/get-workspace-path';
export * from './lib/dependency-versioning';
export * from './lib/register-codelens';
export * from './lib/mcp-json';
export * from './lib/logger';
export * from './lib/git';
export type { GitExtension, API as GitAPI } from './lib/git-extension';
export { isInCursor } from './lib/is-in-cursor';
export { sendMessageToAgent } from './lib/send-message-to-agent';
