name: Test Compatibility with Nx Versions
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  node_version: 24
  NX_CLOUD_ACCESS_TOKEN: ${{ github.ref == 'refs/heads/master' && secrets.NX_CLOUD_READ_WRITE_TOKEN || secrets.NX_CLOUD_READ_TOKEN }}

jobs:
  main-linux:
    name: Main Linux
    runs-on: ubuntu-latest
    env:
      NX_CI_EXECUTION_ENV: 'linux'
      NXLS_E2E_DEFAULT_VERSION: 'canary'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - run: |
          npx nx-cloud start-ci-run --distribute-on="1 linux-medium-js" --with-env-vars="GIT_AUTHOR_EMAIL,GIT_AUTHOR_NAME,GIT_COMMITTER_EMAIL,GIT_COMMITTER_NAME,NX_CI_EXECUTION_ENV,NXLS_E2E_DEFAULT_VERSION,JAVA_VERSION"
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.node_version }}
          check-latest: true
          cache: yarn
      - run: yarn install --immutable
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - run: npx nx run nxls-e2e:e2e-ci --parallel=1

  main-windows:
    name: Main Windows
    runs-on: windows-latest
    env:
      GIT_AUTHOR_EMAIL: test@test.com
      GIT_AUTHOR_NAME: Test
      GIT_COMMITTER_EMAIL: test@test.com
      GIT_COMMITTER_NAME: Test
      NX_CI_EXECUTION_ENV: 'windows'
      NXLS_E2E_DEFAULT_VERSION: 'canary'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: |
          npx nx-cloud start-ci-run --distribute-on="1 windows-medium-js" --with-env-vars="GIT_AUTHOR_EMAIL,GIT_AUTHOR_NAME,GIT_COMMITTER_EMAIL,GIT_COMMITTER_NAME,NX_CI_EXECUTION_ENV,NXLS_E2E_DEFAULT_VERSION,JAVA_VERSION"
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.node_version }}
          check-latest: true
          cache: yarn
      - run: yarn install --immutable
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - run: npx nx run nxls-e2e:e2e-ci --parallel=1
