name: 'run ci and upload artifacts'
on:
  workflow_call:

runs-on: ubuntu-latest
jobs:
  main:
    name: Main
    steps:
      - name: Run Commands
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
        with:
          main-branch-name: 'master'
          number-of-agents: 4
          install-commands: 'yarn install --immutable'
          parallel-commands: |
            yarn exec nx-cloud record -- yarn exec nx workspace-lint
            yarn exec nx-cloud record -- yarn exec nx format:check
          parallel-commands-on-agents: |
            yarn exec nx affected --target=lint --parallel=3 --configuration=ci
            yarn exec nx affected --target=test --parallel=3 --configuration=ci
            yarn exec nx affected --target=build --parallel=3 --configuration=ci
            NX_RUN_GROUP=run-group-e2e-${{ github.run_id}}-${{ github.run_attempt }} yarn exec nx affected --target=e2e --parallel=3 --configuration=ci
          final-commands: |
            NX_RUN_GROUP=run-group-e2e-${{ github.run_id}}-${{ github.run_attempt }} npx nx-cloud stop-all-agents
      - name: Upload artifacts
        shell: bash
        run: ls apps/vscode-e2e/.screenshots
